# 亮度变换参数
brightness:
  # a:亮度值的随机倍数
  a: 30
  # b:亮度值的随机加数
  b: 30
  # 输出最小和最大亮度值
  min: 2
  max: 254
# 图片大小参数
size:
  # 叠加图片在背景图像长宽占百分比
  min: 5
  max: 75
# 模糊处理参数
blur:
  # 高斯滤波范围，模糊处理边长为2r+1，默认1
  r: 0
# 透视变换参数
perspective:
  # 随机宽度范围，指每个角位置变化距离占边长百分比，应介于0-0.5
  range: 0.3
  # 变换对称模式，0即不对称，1为左右对称，2为上下对称。
  # 以正方形为例，对称将只会把正方形透视变换为等腰梯形，左右对称则左右两边长度相等上下两边平行，上下对称则上下两边长度相等左右两边跑平行。
  mode: 0
  # 对称方向指定，仅当开启对称情况下有效，0即不指定。
  # 若前一参数对称模式为1即左右对称，此参数为1表示等腰梯形上窄下宽，此参数为2反之.
  # 若前一参数对称模式为2即上下对称，此参数为1表示等腰梯形左宽右窄，此参数为2反之.
  direction: 0
# 输出数据格式。可选项：yolo / voc
format: yolo